language: python

os: linux

python:
    - "3.6"

install:
    - pip install --user codecov
    - pip install pytest-cov
    - pip install -e .

script:
    - pytest --cov=./

after_success:
    - codecov -t df7f6710-c803-4ea6-a1c1-1f00cd1d4073
