language: python

os: linux

python:
    - "3.6"

install:
    - pip install --user codecov
    - pip install pytest pytest-cov
    - pip install -e .

script:
    - pytest --cov=./

after_success:
    - codecov
